### ISSUE TITLE
'what is the weather in baltimore' returns an error #30

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/selene_api#31]
I re-open here according to https://github.com/OpenVoiceOS/skill-ovos-weather/issues/30#issuecomment-1494854965 comment.
```
2023-03-28 15:55:03.544 - skill-ovos-weather.openvoiceos - ERROR - Unexpected error retrieving weather
Traceback (most recent call last):
  File "/home/ovos/.local/share/mycroft/skills/skill-ovos-weather.openvoiceos/__init__.py", line 1042, in _get_weather
    latitude, longitude = self._determine_weather_location(intent_data)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.local/share/mycroft/skills/skill-ovos-weather.openvoiceos/__init__.py", line 1086, in _determine_weather_location
    latitude = intent_data.geolocation["latitude"]
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.local/share/mycroft/skills/skill-ovos-weather.openvoiceos/skill/intent.py", line 56, in geolocation
    self._geolocation = get_geolocation(self.location)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.local/share/mycroft/skills/skill-ovos-weather.openvoiceos/skill/util.py", line 105, in get_geolocation
    geolocation = geolocation_api.get_geolocation(location)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/mycroft/deprecated/api.py", line 184, in get_geolocation
    return self._real_api.get_geolocation(location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_backend_client/api.py", line 351, in get_geolocation
    return self.backend.geolocation_get(location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_backend_client/backends/offline.py", line 171, in geolocation_get
    "code": details["addresstags"].get("postcode") or details["calculated_postcode"] or "",
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
```

**Comment by emphasize** [comment]
Just a heads up, this is location specific. if no addresstags are available for this location, an empty list is sent instead of a dict.
I`ll wait with the PR until the sql stuff is settled.

If you don't want to wait [#](https://github.com/OpenVoiceOS/ovos-backend-client/blob/529a325a89ad6a13b08ff063e0244a19dedaf39b/ovos_backend_client/backends/offline.py#L171)

```python
        # if no addresstags are present for the location an empty list is sent instead of a dict
        if not details.get("addresstags"):
            details["addresstags"] = dict()

        location = {
            "city": {
                "code": details.get("addresstags", {}).get("postcode") or \
                        details.get("calculated_postcode") or "",
                "name": details.get("localname"),
                "state": {
                    "code": details.get("addresstags", {}).get("state_code") or \
                            details.get("calculated_postcode") or "",
                    "name": details.get("addresstags", {}).get("state") or \
                            data.get("display_name", "").split(", ")[0] or "",
                    "country": {
                        "code": details.get("country_code", "").upper() or \
                                details.get("addresstags", {}).get("country") or "",
                        "name": data.get("display_name", "").split(", ")[-1]
                    }
                }
            },
            "coordinate": {
                "latitude": data.get("lat"),
                "longitude": data.get("lon")
            },
            "timezone": self._get_timezone(lat=data.get("lat"),
                                           lon=data.get("lon"))
        }
        return location

```
