### ISSUE TITLE
Unable to upload wake word.

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/selene_api#47]
Configuration:
```json
  "listener": {
    "wake_word_upload": {
      "disable": false,
      "url": "http://127.0.0.1:5000/precise/upload"
    }
  },
 "opt_in": true 
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_dinkum_listener/service.py", line 447, in upload
2023-08-17 22:03:39.796 - voice - ovos_dinkum_listener.service:_hotword_audio:511 - DEBUG - Handling listen sound: /home/ovos/.venv/lib/python3.11/site-packages/ovos_dinkum_listener/res/snd/start_listening.wav
    DatasetApi().upload_wake_word(wav_data,
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_backend_client/api.py", line 568, in upload_wake_word
    return self.backend.dataset_upload_wake_word(audio, params, upload_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_backend_client/backends/offline.py", line 390, in dataset_upload_wake_word
    byte_data = audio.get_wav_data()
                ^^^^^^^^^^^^^^^^^^
AttributeError: 'bytes' object has no attribute 'get_wav_data'
```

**Comment by emphasize** [comment]
those are bytes passed to `_upload_hotword`

we would need to convert it like
```python
listener = self.config.get("listener", {}) 
audio = AudioData(audio_bytes,
                  sample_rate=listerner.get("sample_rate", 16000),
                  sample_width=listerner.get("sample_width", 2))
```

**Comment by JarbasAl** [comment]
fixed in https://github.com/OpenVoiceOS/ovos-backend-client/pull/48

**Comment by emphasize** [comment]
@JarbasAl also needs a fix in [personal](https://github.com/OpenVoiceOS/ovos-backend-client/blob/d8f03aa61f10697e0a03ed667a297db19d707c32/ovos_backend_client/backends/personal.py#L317)
